---
- name: apache web service
  hosts: server1
  become: true
  become_method: sudo
  become_user: root
  tasks:

- name: Deploy and start Apache HTTPD service
  hosts: webserver
  vars:
   web_pkg: httpd
   firewall_pkg: firewalld
   web_service: httpd
   firewall_service: firewalld
   python_pkg: python-httplib2
   rule: http

  tasks:
  - name: Required packages are installed and up to date
    yum:
      name:
       - "{{ web_pkg }}"
       - "{{ firewall_pkg }}"
       - "{{ python_pkg }}"
      state: latest

  - name: The {{ firewall_service }} service is started and enabled
    service:
     name: "{{ firewall_service }}"
     enabled: true
     state: started
  - name: The {{ web_service }} service is started and enabled
    service:
     name: "{{ web_service }}"
     enabled: true
     state: started
